### ISSUE TITLE
Page Object model patten

### ISSUE THREAD

**Issue by cmacdonnacha** [MarcusFelling/Demo.Playwright#4]
Just wondering if you have any tests showing the use of a Page Object Model pattern?

**Comment by MarcusFelling** [comment]
Check out the tests here: https://github.com/MarcusFelling/Demo.Playwright/tree/main/basic/pom

**Comment by MarcusFelling** [comment]
@cmacdonnacha - does that example help, or are you looking for something more specific?

**Comment by cmacdonnacha** [comment]
Yep that's perfect thanks a lot.
